### ISSUE TITLE
Useless pings

### ISSUE THREAD

**Issue by Dorukyum** [The-Coding-Realm/coding-bot-v4#11]
**The problem**
Sometimes half of the server gets pinged by the "helper" command for the most basic errors.

**My idea for the solution**
The bot can first ping On Patrol Helper and wait for 20 seconds, if nobody responds, then ping the related coding help role.

**Additional context**
I can fork and create a pull request if you approve this idea.

**Comment by BobDotCom** [comment]
I think we've been looking at other ideas too, but we'll keep this in mind as well.

**Comment by Dorukyum** [comment]
Yes, I've seen the other ideas for the help procedure but we can use this one until we agree on a new process.

**Comment by BobDotCom** [comment]
If you wanna make a pr I'd be open to the idea of using it (or something pretty similar) for now.

**Comment by BobDotCom** [comment]
I'd suggest it does this:

1. user asks for help
2. message sent to channel x, mentioning the particular help role (the channel will only be visible by on patrol helpers)
3. message sent to channel y (mentioning the particular help role), after 5 minutes if an on patrol helper didn't mark it as complete yet

I can add channel ids in later. I'd also be ok with doing it myself if you end up not wanting to.

**Comment by SohamGhugare** [comment]
Rather than this, make it so when they pass on a help, it will be sent to either of a help channel (a,b,c,d,e). If noone responds to the help within 15-20 mins, ping the on-patrol-helpers, if they dont respond, then ping the specific helper role after 25-30 mins. This would minimize pings for both on-patrol helpers and specific lang helpers, because if someone is already there in the help channel they can handle the help instead of pinging anyone

**Comment by NightZan999** [comment]
> Rather than this, make it so when they pass on a help, it will be sent to either of a help channel (a,b,c,d,e). If noone responds to the help within 15-20 mins, ping the on-patrol-helpers, if they dont respond, then ping the specific helper role after 25-30 mins. This would minimize pings for both on-patrol helpers and specific lang helpers, because if someone is already there in the help channel they can handle the help instead of pinging anyone

I agree with the approach of pings and stuff, **but a better solution would be this:**
> First you also create a claiming system in which a helper can claim a channel, if claimed no more help is to be posted in that channel. The bot can append this to a list which can be a property of the bot variable itself. 

Then after that it checks if all channels are claimed or not, and then picks a channel. The second the helper has finished helping someone you can unclaim the channel which removes the channel ID from the list. 

This way the bot also doesn't interfere / ping in the middle of a helper talking bigbrain stuff to members.
Also let mods claim and unclaim help channels cuz yes

**Comment by Dorukyum** [comment]
Closing as this system isn't used anymore.
